import React, { useState } from 'react';
import { ghanaianFoods, HealthCondition } from '../data/ghanaianFoods';
import { CheckCircle2, XCircle, RefreshCw, Star, ChevronRight, Sparkles, Printer } from 'lucide-react';

interface DietResultsProps {
  condition: HealthCondition;
}

export const DietResults: React.FC<DietResultsProps> = ({ condition }) => {
  const [activeTab, setActiveTab] = useState<'recommended' | 'avoid'>('recommended');
  const [savedMeals, setSavedMeals] = useState<string[]>([]);

  const recommendedFoods = ghanaianFoods.filter((food) =>
    food.suitableFor.includes(condition.id)
  );

  const avoidFoods = ghanaianFoods.filter((food) =>
    food.avoidFor.includes(condition.id)
  );

  const toggleSaveMeal = (id: string) => {
    setSavedMeals((prev) =>
      prev.includes(id) ? prev.filter((item) => item !== id) : [...prev, id]
    );
  };

  const downloadDietPlan = () => {
    const textContent = `
=== EATSMART GHANA DIET PLAN ===
Condition: ${condition.name}

RECOMMENDED GHANAIAN MEALS:
${recommendedFoods.map(f => `- ${f.name}: ${f.reasons[condition.id] || ''}`).join('\n')}

MEALS TO AVOID/RESTRICT:
${avoidFoods.map(f => `- ${f.name}: ${f.reasons[condition.id] || ''}`).join('\n')}

Disclaimer: ${condition.disclaimer}
Generated by EatSmart Ghana. Always consult your doctor before making major dietary changes.
    `;
    const element = document.createElement("a");
    const file = new Blob([textContent], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `${condition.name.replace(/\s+/g, '_')}_DietPlan.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-8">
      {/* Result Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center border-b border-slate-100 pb-6 mb-8 gap-4">
        <div>
          <span className="text-xs font-bold text-emerald-600 bg-emerald-50 px-3 py-1 rounded-full uppercase tracking-wider">
            Recommendations for
          </span>
          <h2 className="text-3xl font-extrabold text-slate-900 mt-2 flex items-center gap-2">
            {condition.name}
          </h2>
          <p className="text-slate-500 mt-1 max-w-xl">{condition.description}</p>
        </div>

        <button
          onClick={downloadDietPlan}
          className="px-5 py-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl shadow-sm transition-all duration-150 flex items-center gap-2 text-sm font-semibold"
        >
          <Printer className="w-4 h-4" />
          Download Diet Plan (.txt)
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-slate-100 mb-8">
        <button
          onClick={() => setActiveTab('recommended')}
          className={`flex items-center gap-2 pb-4 text-sm font-bold border-b-2 px-4 transition-all ${
            activeTab === 'recommended'
              ? 'border-emerald-600 text-emerald-600'
              : 'border-transparent text-slate-400 hover:text-slate-600'
          }`}
        >
          <CheckCircle2 className="w-5 h-5 text-emerald-500" />
          Recommended Foods ({recommendedFoods.length})
        </button>

        <button
          onClick={() => setActiveTab('avoid')}
          className={`flex items-center gap-2 pb-4 text-sm font-bold border-b-2 px-4 transition-all ${
            activeTab === 'avoid'
              ? 'border-rose-600 text-rose-600'
              : 'border-transparent text-slate-400 hover:text-slate-600'
          }`}
        >
          <XCircle className="w-5 h-5 text-rose-500" />
          Foods to Avoid ({avoidFoods.length})
        </button>
      </div>

      {/* Recommended Foods Tab */}
      {activeTab === 'recommended' && (
        <div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {recommendedFoods.map((food) => {
              const isSaved = savedMeals.includes(food.id);
              return (
                <div key={food.id} className="border border-slate-100 rounded-2xl p-5 hover:shadow-md transition-all flex flex-col justify-between bg-emerald-50/10">
                  <div>
                    <div className="flex justify-between items-start gap-4 mb-3">
                      <h3 className="font-bold text-xl text-slate-800">{food.name}</h3>
                      <button
                        onClick={() => toggleSaveMeal(food.id)}
                        className={`p-2 rounded-xl border border-slate-100 transition-all ${
                          isSaved ? 'bg-amber-500 text-white border-transparent shadow-sm' : 'bg-white text-slate-400 hover:bg-slate-50'
                        }`}
                      >
                        <Star className="w-4 h-4" fill={isSaved ? "currentColor" : "none"} />
                      </button>
                    </div>

                    <span className="inline-block text-xs font-semibold px-2.5 py-1 rounded-md bg-white border border-slate-100 text-slate-600 mb-3">
                      {food.category}
                    </span>

                    <p className="text-slate-600 text-sm font-light mb-4">{food.description}</p>

                    <div className="p-4 bg-white border border-emerald-100/50 rounded-xl mb-4">
                      <h4 className="text-xs font-bold text-emerald-700 flex items-center gap-1 mb-1">
                        <Sparkles className="w-3.5 h-3.5" /> WHY IT HELPS:
                      </h4>
                      <p className="text-slate-700 text-sm font-medium leading-relaxed">
                        {food.reasons[condition.id] || "Excellent nutritious addition to your health regime."}
                      </p>
                    </div>

                    {food.substitutes && food.substitutes.length > 0 && (
                      <div className="text-xs text-slate-500 flex items-center gap-1.5 mb-4 px-2 py-1.5 bg-white border border-slate-100 rounded-lg">
                        <RefreshCw className="w-3.5 h-3.5 text-slate-400" />
                        Healthy alternatives: <span className="font-semibold text-slate-700">{food.substitutes.join(', ')}</span>
                      </div>
                    )}
                  </div>

                  {/* Nutrition Summary */}
                  <div className="border-t border-slate-100 pt-4 mt-4 grid grid-cols-3 gap-2 text-center">
                    <div className="p-2 bg-white rounded-xl border border-slate-100">
                      <div className="text-xs text-slate-400 font-medium">Glycemic</div>
                      <div className={`text-sm font-bold ${
                        food.nutritionalValue.glycemicIndex === 'Low' ? 'text-emerald-600' : 'text-amber-500'
                      }`}>{food.nutritionalValue.glycemicIndex}</div>
                    </div>

                    <div className="p-2 bg-white rounded-xl border border-slate-100">
                      <div className="text-xs text-slate-400 font-medium">Protein</div>
                      <div className="text-sm font-bold text-slate-700">{food.nutritionalValue.protein}g</div>
                    </div>

                    <div className="p-2 bg-white rounded-xl border border-slate-100">
                      <div className="text-xs text-slate-400 font-medium">Calories</div>
                      <div className="text-sm font-bold text-slate-700">{food.nutritionalValue.calories} kcal</div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {recommendedFoods.length === 0 && (
            <div className="text-center py-12 text-slate-500 font-light">
              No specific recommendations listed for this category.
            </div>
          )}
        </div>
      )}

      {/* Avoid Foods Tab */}
      {activeTab === 'avoid' && (
        <div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {avoidFoods.map((food) => (
              <div key={food.id} className="border border-slate-100 rounded-2xl p-5 hover:shadow-md transition-all flex flex-col justify-between bg-rose-50/10 border-rose-100/40">
                <div>
                  <h3 className="font-bold text-xl text-slate-800 mb-2 flex items-center gap-2">
                    {food.name}
                    <span className="text-xs font-bold text-rose-600 bg-rose-50 px-2 py-0.5 rounded-md border border-rose-100">
                      RESTRICT
                    </span>
                  </h3>

                  <p className="text-slate-600 text-sm font-light mb-4">{food.description}</p>

                  <div className="p-4 bg-white border border-rose-100/50 rounded-xl mb-4">
                    <h4 className="text-xs font-bold text-rose-700 flex items-center gap-1 mb-1">
                      <XCircle className="w-3.5 h-3.5" /> WHY TO AVOID / LIMIT:
                    </h4>
                    <p className="text-slate-700 text-sm font-medium leading-relaxed">
                      {food.reasons[condition.id] || "May trigger blood sugar spikes or raise blood pressure."}
                    </p>
                  </div>
                </div>

                <div className="border-t border-slate-100 pt-4 mt-4 grid grid-cols-3 gap-2 text-center">
                  <div className="p-2 bg-white rounded-xl border border-slate-100">
                    <div className="text-xs text-slate-400 font-medium">Sodium</div>
                    <div className={`text-sm font-bold ${food.nutritionalValue.sodium === 'High' ? 'text-rose-600' : 'text-slate-600'}`}>{food.nutritionalValue.sodium}</div>
                  </div>
                  <div className="p-2 bg-white rounded-xl border border-slate-100">
                    <div className="text-xs text-slate-400 font-medium">Glycemic</div>
                    <div className={`text-sm font-bold ${food.nutritionalValue.glycemicIndex === 'High' ? 'text-rose-600' : 'text-slate-600'}`}>{food.nutritionalValue.glycemicIndex}</div>
                  </div>
                  <div className="p-2 bg-white rounded-xl border border-slate-100">
                    <div className="text-xs text-slate-400 font-medium">Calories</div>
                    <div className="text-sm font-bold text-slate-700">{food.nutritionalValue.calories} kcal</div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {avoidFoods.length === 0 && (
            <div className="text-center py-12 text-slate-500 font-light">
              No major restrictions listed. Always moderate your portion sizes!
            </div>
          )}
        </div>
      )}

      {/* Localized Meal Prep Tips */}
      <div className="mt-12 p-6 rounded-2xl bg-slate-900 text-white flex flex-col md:flex-row gap-6 items-center justify-between shadow-lg">
        <div className="max-w-xl">
          <h4 className="font-bold text-xl mb-2 flex items-center gap-2 text-amber-300">
            💡 Local Cooking Tips for {condition.name}
          </h4>
          <p className="text-sm text-slate-300 font-light leading-relaxed">
            Many Ghanaian dishes become risky purely due to commercial seasonings and heavy palm oil. By preparing these at home, you have 100% control over the salt, oil, and portion sizes.
          </p>
        </div>
        <ChevronRight className="w-8 h-8 text-amber-300 hidden md:block" />
      </div>
    </div>
  );
};
